# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 341)
        MainWindow.setStyleSheet("background-color: #2b2b2b;\n"
"border-radius: 10px;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(130, -10, 75, 51))
        self.start.setStyleSheet("background-color: #2c2c2c; \n"
"color: white;\n"
"border-radius: 8px; ")
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(210, -10, 75, 51))
        self.stop.setStyleSheet("background-color: #2c2c2c; \n"
"color: white;\n"
"border-radius: 8px; ")
        self.stop.setObjectName("stop")
        self.video = QVideoWidget(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(440, 50, 441, 231))
        self.video.setObjectName("video")
        self.autostart = QtWidgets.QCheckBox(self.centralwidget)
        self.autostart.setGeometry(QtCore.QRect(300, -10, 121, 51))
        self.autostart.setStyleSheet("color: white;\n"
"width: 16px;\n"
"height: 16px;\n"
"border-radius: 3px;\n"
"background: #2c2c2c;")
        self.autostart.setObjectName("autostart")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 50, 441, 241))
        self.calendarWidget.setObjectName("calendarWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "START"))
        self.stop.setText(_translate("MainWindow", "STOP"))
        self.autostart.setText(_translate("MainWindow", "AUTOSTART"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
